-- A deck someone wrote: this week's spelling words, capitals, vocabulary. The
-- built-in maths facts are generated by the app and have no row here. `cards`
-- is a JSON array of {"q": "...", "a": "..."}, stored whole so that saving a
-- deck is one write. mode is 'cards' (a prompt and a typed answer) or
-- 'spelling' (the word is read aloud). visibility is 'everyone' or 'mine'.
CREATE TABLE IF NOT EXISTS app_practice_decks__decks (
  id         TEXT PRIMARY KEY,
  title      TEXT NOT NULL,
  mode       TEXT NOT NULL,
  cards      TEXT NOT NULL,
  visibility TEXT NOT NULL DEFAULT 'everyone',
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Serves the first-render read: newest deck first.
CREATE INDEX IF NOT EXISTS app_practice_decks__decks_created_idx
  ON app_practice_decks__decks (created_at DESC, id DESC);

-- One finished run. deck_key names what was practised: 'math:mul:only:7' for
-- a built-in set, 'deck:<id>' for a written one. A member inserts their own
-- runs and cannot change them afterwards (see `runs` in manifest.json).
-- missed_count is the number of cards not answered right first time.
CREATE TABLE IF NOT EXISTS app_practice_decks__runs (
  id           TEXT PRIMARY KEY,
  member_id    TEXT NOT NULL,
  deck_key     TEXT NOT NULL,
  label        TEXT NOT NULL DEFAULT '',
  card_count   INTEGER NOT NULL,
  missed_count INTEGER NOT NULL DEFAULT 0,
  duration_ms  INTEGER NOT NULL,
  run_date     TEXT NOT NULL,
  created_at   TEXT NOT NULL
);

-- Serves a member's recent runs, newest first.
CREATE INDEX IF NOT EXISTS app_practice_decks__runs_member_recent_idx
  ON app_practice_decks__runs (member_id, created_at DESC);

-- Serves the glance: a member's runs since Monday.
CREATE INDEX IF NOT EXISTS app_practice_decks__runs_member_date_idx
  ON app_practice_decks__runs (member_id, run_date);

-- Serves the family view and the daily expiry of old runs.
CREATE INDEX IF NOT EXISTS app_practice_decks__runs_created_idx
  ON app_practice_decks__runs (created_at DESC);

-- A member's best time for one set at one length. Kept beside `runs` so the
-- first screen reads one row per set instead of every run ever finished, and
-- so a best survives after the run that set it has expired.
CREATE TABLE IF NOT EXISTS app_practice_decks__bests (
  id         TEXT PRIMARY KEY,
  member_id  TEXT NOT NULL,
  deck_key   TEXT NOT NULL,
  card_count INTEGER NOT NULL,
  label      TEXT NOT NULL DEFAULT '',
  best_ms    INTEGER NOT NULL,
  best_date  TEXT NOT NULL,
  run_count  INTEGER NOT NULL DEFAULT 1,
  last_date  TEXT NOT NULL,
  UNIQUE (member_id, deck_key, card_count)
);

-- Serves the first-render read: a member's sets, most recently practised first.
CREATE INDEX IF NOT EXISTS app_practice_decks__bests_member_recent_idx
  ON app_practice_decks__bests (member_id, last_date DESC, deck_key);

-- Serves the family view: every member's sets, most recently practised first.
CREATE INDEX IF NOT EXISTS app_practice_decks__bests_recent_idx
  ON app_practice_decks__bests (last_date DESC, member_id);
